name: piwo
description: Library that generates interface from you HTTP API.
version: 0.0.1
author: DrunkDevs
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  source_gen: ^0.9.3
  http: ^0.12.0

dev_dependencies:
  test: '>=0.12.42 <2.0.0'

cache:
  directories:
    - $HOME/.pub-cache
